#!/bin/bash
#
# Unix cross compile helper script
# (C) Nettle developers 2000-2001
#
# $Id$

lib=$1
cross_path=$2

if [ "$cross_path" == "" ] ; then
  cross_path=/home/riscos
fi  


if [ "$lib" == "-scl" ] ; then

  if [ ! -e $cross_path/lib/netlib ] ; then
    echo Cannot find Netlib in $cross_path/lib/netlib
    exit 1
  fi

  # For NetLib's "Internet:file.h"includes
  export INTERNET_PATH=$cross_path/lib/netlib
  library=scl

else
  library=unixlib

fi


rm *.o *.c *.h *.s 2>/dev/null

for i in c h s
do
  cd $i
  for j in *
  do
    if [ "$j" != "CVS" ]
    then
      cp -a $j ../$j.$i
    fi
  done
  cd -
done


make -f MakeCross GCCDIR=$cross_path NETLIB=$INTERNET_PATH LIB=$library
